openapi: 3.0.1
info:
  description: Tracking API
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "Tracking API"
  version: 1.0.0

paths:
  "/api/next-tracking-number":
    get:
      operationId: nextTrackingNumber
      tags: ["Tracking"]
      parameters:
        - in: query
          name: origin_country_id
          required: true
          schema:
            type: string
        - in: query
          name: destination_country_id
          required: true
          schema:
            type: string
        - in: query
          name: weight
          required: false
          schema:
            format: double
            type: string
        - in: query
          name: created_at
          required: false
          schema:
            type: string
        - in: query
          name: customer_id
          required: true
          schema:
            type: string
        - in: query
          name: customer_name
          required: false
          schema:
            type: string
        - in: query
          name: customer_slug
          required: false
          schema:
            type: string    
      responses:
        200:
          description: "Get Tracking Number"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrackingNumber"
            application/xml:
              schema:
                $ref: "#/components/schemas/TrackingNumber"
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
components:
  schemas:
    TrackingNumber:
      description: Tracking Number.
      properties:
        tracking_number:
          type: string
        created_at:
          type: string